# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Letsmeet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Letsmeet
  pod 'GoogleSignIn'
  pod 'NVActivityIndicatorView'
  pod 'DatePicker', '~> 1.3.0'
  pod 'GoogleAPIClientForREST/Calendar'
  pod 'Alamofire', '~> 5.5'
end
