name: Deploys backend to elastic beanstalk
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: elastic beanstalk deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: generate deployment package
        run: cd backend && zip -r ../deploy.zip . && cd ..

      - name: generate uuid
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1

      - name: deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEy }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: cs130project
          environment_name: Cs130project-env
          version_label: ${{ steps.generate-uuid.outputs.uuid }}
          region: us-east-1
          deployment_package: deploy.zip


